### PR TITLE
fix: updating Storybook example to pass a11y checks

### PR DESCRIPTION
**Pull request by ccedrone**

### CODE REVIEW

**Comment by silvalaura** [comment]
In storybook, I'm still seeing `1 Violation` for all examples if I refresh the page:
image
image

It seems to be related to the color contrast for the alert (we get the same violation under the [Alerts stories](https://storybook-preview-864--upbeat-sinoussi-f675aa.netlify.app/?path=/story/alert--default)). @orion-cengage thoughts?

**Comment by ccedrone** [comment]
Strange, I can't reproduce for the Inverse example, however the others show an error, which is reading a different color for the foreground on each page load.

**Comment by silvalaura** [comment]
> Strange, I can't reproduce for the Inverse example, however the others show an error, which is reading a different color for the foreground on each page load.

To reproduce the Inverse violation, go directly to https://storybook-preview-864--upbeat-sinoussi-f675aa.netlify.app/?path=/story/container--inverse (instead of going to Default first and then Inverse)

**Comment by ccedrone** [comment]
Still doesn't reproduce the error for me.

**Comment by ccedrone** [comment]
PR unnecessary due to Storybook issues.

**Pull request closed without merging**
